/*
  javascript.util is a port of selected parts of java.util to JavaScript which
  main purpose is to ease porting Java code to JavaScript.

  Copyright (C) 2011 by Björn Harrtell

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/
(function() {var c=null;function d(){return function(){}}function e(a,b){var i=a.split("."),o=window;!(i[0]in o)&&o.execScript&&o.execScript("var "+i[0]);for(var q;i.length&&(q=i.shift());)!i.length&&b!==void 0?o[q]=b:o=o[q]?o[q]:o[q]={}}e("javascript.util.version","0.5.0");function f(a){this.message=a||""}e("javascript.util.OperationNotSupported",f);f.prototype=Error();f.prototype.name="OperationNotSupported";f.prototype.name=f.prototype.name;function g(a){this.message=a||""}
e("javascript.util.IndexOutOfBoundsException",g);g.prototype=Error();g.prototype.name="IndexOutOfBoundsException";g.prototype.name=g.prototype.name;function h(a){this.message=a||""}e("javascript.util.NoSuchElementException",h);h.prototype=Error();h.prototype.name="NoSuchElementException";h.prototype.name=h.prototype.name;function j(a){this.message=a||""}e("javascript.util.EmptyStackException",j);j.prototype=Error();j.prototype.name="EmptyStackException";j.prototype.name=j.prototype.name;
function k(){}e("javascript.util.Map",k);k.prototype.get=d();k.prototype.get=k.prototype.get;k.prototype.put=d();k.prototype.put=k.prototype.put;k.prototype.size=d();k.prototype.size=k.prototype.size;k.prototype.b=d();k.prototype.values=k.prototype.b;e("javascript.util.SortedMap",d());function l(){}e("javascript.util.Iterator",l);l.prototype.c=d();l.prototype.hasNext=l.prototype.c;l.prototype.next=d();l.prototype.next=l.prototype.next;l.prototype.remove=d();l.prototype.remove=l.prototype.remove;
function m(){}e("javascript.util.Collection",m);m.prototype.add=d();m.prototype.add=m.prototype.add;m.prototype.e=d();m.prototype.isEmpty=m.prototype.e;m.prototype.d=d();m.prototype.iterator=m.prototype.d;m.prototype.size=d();m.prototype.size=m.prototype.size;m.prototype.f=d();m.prototype.toArray=m.prototype.f;function n(){}e("javascript.util.List",n);n.prototype=new m;n.prototype.get=d();n.prototype.get=n.prototype.get;n.prototype.g=d();n.prototype.addAll=n.prototype.g;
function p(a){this.a=[];a instanceof m&&this.g(a)}e("javascript.util.ArrayList",p);p.prototype=new n;p.prototype.a=c;p.prototype.add=function(a){this.a.push(a);return!0};p.prototype.add=p.prototype.add;p.prototype.g=function(a){for(a=a.d();a.c();)this.add(a.next());return!0};p.prototype.addAll=p.prototype.g;p.prototype.d=function(){return new r(this)};p.prototype.iterator=p.prototype.d;p.prototype.get=function(a){if(a<0||a>=this.size())throw new g;return this.a[a]};p.prototype.get=p.prototype.get;
p.prototype.e=function(){return this.a.length===0};p.prototype.isEmpty=p.prototype.e;p.prototype.size=function(){return this.a.length};p.prototype.size=p.prototype.size;p.prototype.f=function(){for(var a=[],b=0;b<this.a.length;b++)a.push(this.a[b]);return a};p.prototype.toArray=p.prototype.f;function r(a){this.h=a}p.Iterator=r;r.prototype.h=c;r.prototype.position=0;r.prototype.next=function(){if(this.position===this.h.size())throw new h;return this.h.get(this.position++)};r.prototype.next=r.prototype.next;
r.prototype.c=function(){return this.position<this.h.size()?!0:!1};r.prototype.hasNext=r.prototype.c;r.prototype.remove=function(){throw new f;};r.prototype.remove=r.prototype.remove;function s(){this.object={}}e("javascript.util.HashMap",s);s.prototype.object=c;s.prototype.get=function(a){return this.object[a]||c};s.prototype.get=s.prototype.get;s.prototype.put=function(a,b){return this.object[a]=b};s.prototype.put=s.prototype.put;
s.prototype.b=function(){var a=new p,b;for(b in this.object)this.object.hasOwnProperty(b)&&a.add(this.object[b]);return a};s.prototype.values=s.prototype.b;s.prototype.size=function(){return this.b().size()};s.prototype.size=s.prototype.size;function t(){}e("javascript.util.Set",t);t.prototype.contains=d();t.prototype.contains=t.prototype.contains;e("javascript.util.SortedSet",d());function u(){this.a=[]}e("javascript.util.TreeSet",u);u.prototype.a=c;
u.prototype.contains=function(a){for(var b=0;b<this.a.length;b++)if(this.a[b].compareTo(a)===0)return!0;return!1};u.prototype.contains=u.prototype.contains;u.prototype.add=function(a){if(this.contains(a))return!1;for(var b=0;b<this.a.length;b++)if(this.a[b].compareTo(a)===1)return this.a.splice(b,0,a),!0;this.a.push(a);return!0};u.prototype.add=u.prototype.add;u.prototype.size=function(){return this.a.length};u.prototype.size=u.prototype.size;u.prototype.e=function(){return this.a.length===0};
u.prototype.isEmpty=u.prototype.e;u.prototype.f=function(){for(var a=[],b=0;b<this.a.length;b++)a.push(this.a[b]);return a};u.prototype.toArray=u.prototype.f;u.prototype.d=function(){return new v(this)};u.prototype.iterator=u.prototype.d;function v(a){this.i=a}u.Iterator=v;v.prototype.i=c;v.prototype.position=0;v.prototype.next=function(){if(this.position===this.i.size())throw new h;return this.i.a[this.position++]};v.prototype.next=v.prototype.next;
v.prototype.c=function(){return this.position<this.i.size()?!0:!1};v.prototype.hasNext=v.prototype.c;v.prototype.remove=function(){throw new f;};v.prototype.remove=v.prototype.remove;function w(){this.a=[]}e("javascript.util.Stack",w);w.prototype=new n;w.prototype.a=c;w.prototype.push=function(a){this.a.push(a);return a};w.prototype.push=w.prototype.push;w.prototype.pop=function(){if(this.a.length===0)throw new j;return this.a.pop()};w.prototype.pop=w.prototype.pop;
w.prototype.j=function(){if(this.a.length===0)throw new j;return this.a[this.a.length-1]};w.prototype.peek=w.prototype.j;w.prototype.empty=function(){return this.a.length===0?!0:!1};w.prototype.empty=w.prototype.empty;w.prototype.search=function(a){return this.a.indexOf(a)};w.prototype.search=w.prototype.search;w.prototype.size=function(){return this.a.length};w.prototype.size=w.prototype.size;function x(){this.a=[]}e("javascript.util.TreeMap",x);x.prototype.a=c;
x.prototype.get=function(a){for(var b=0;b<this.a.length;b++){var i=this.a[b];if(i.key.compareTo(a)===0)return i.value}return c};x.prototype.get=x.prototype.get;x.prototype.put=function(a,b){var i=this.get(a);if(i){var o=i.value;i.value=b;return o}for(var o={key:a,value:b},q=0;q<this.a.length;q++)if(i=this.a[q],i.key.compareTo(a)===1)return this.a.splice(q,0,o),c;this.a.push({key:a,value:b});return c};x.prototype.put=x.prototype.put;
x.prototype.b=function(){for(var a=new p,b=0;b<this.a.length;b++)a.add(this.a[b].value);return a};x.prototype.values=x.prototype.b;x.prototype.size=function(){return this.b().size()};x.prototype.size=x.prototype.size;})();
