name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set Node.js Version
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Determine Cache Directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Configure Job Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ github.event.release.tag_name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ github.event.release.tag_name }}-
      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
